export const GET_ORIGINALS = "GET_ORIGINALS";
export const GET_TRENDING = "GET_TRENDING";
export const GET_TOPRATED = "GET_TOPRATED";
export const GET_ACTION = "GET_ACTION";
export const GET_COMEDY = "GET_COMEDY";
export const GET_HORROR = "GET_HORROR";
export const GET_ROMANCE = "GET_ROMANCE";
export const GET_DOCUMENTARIES = "GET_DOCUMENTARIES";

export const SET_MOVIEDETAIL = "SET_MOVIEDETAIL";

export const SEARCH_MOVIE = "SEARCH_MOVIE"

// LOGIN
export const LOGIN_USER = "LOGIN_USER"
//LOGOUT
export const LOGOUT_USER = "LOGOUT_USER"